/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as LiveRouteImport } from "./routes/live"
import { Route as ChatRouteImport } from "./routes/chat"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProjectsIndexRouteImport } from "./routes/projects/index"
import { Route as ExperimentsIndexRouteImport } from "./routes/experiments/index"
import { Route as ProjectsProjectKeyRouteImport } from "./routes/projects/$projectKey"
import { Route as ProjectsProjectKeyIndexRouteImport } from "./routes/projects/$projectKey/index"
import { Route as ProjectsProjectKeyWorkspaceRouteImport } from "./routes/projects/$projectKey/workspace"
import { Route as ProjectsProjectKeyReviewsRouteImport } from "./routes/projects/$projectKey/reviews"
import { Route as ProjectsProjectKeyMemoryRouteImport } from "./routes/projects/$projectKey/memory"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: "/live",
  path: "/live",
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: "/experiments/",
  path: "/experiments/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: "/projects/$projectKey",
  path: "/projects/$projectKey",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectKeyIndexRoute = ProjectsProjectKeyIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProjectsProjectKeyRoute,
} as any)
const ProjectsProjectKeyWorkspaceRoute =
  ProjectsProjectKeyWorkspaceRouteImport.update({
    id: "/workspace",
    path: "/workspace",
    getParentRoute: () => ProjectsProjectKeyRoute,
  } as any)
const ProjectsProjectKeyReviewsRoute =
  ProjectsProjectKeyReviewsRouteImport.update({
    id: "/reviews",
    path: "/reviews",
    getParentRoute: () => ProjectsProjectKeyRoute,
  } as any)
const ProjectsProjectKeyMemoryRoute =
  ProjectsProjectKeyMemoryRouteImport.update({
    id: "/memory",
    path: "/memory",
    getParentRoute: () => ProjectsProjectKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/chat": typeof ChatRoute
  "/live": typeof LiveRoute
  "/settings": typeof SettingsRoute
  "/projects/$projectKey": typeof ProjectsProjectKeyRouteWithChildren
  "/experiments/": typeof ExperimentsIndexRoute
  "/projects/": typeof ProjectsIndexRoute
  "/projects/$projectKey/memory": typeof ProjectsProjectKeyMemoryRoute
  "/projects/$projectKey/reviews": typeof ProjectsProjectKeyReviewsRoute
  "/projects/$projectKey/workspace": typeof ProjectsProjectKeyWorkspaceRoute
  "/projects/$projectKey/": typeof ProjectsProjectKeyIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/chat": typeof ChatRoute
  "/live": typeof LiveRoute
  "/settings": typeof SettingsRoute
  "/experiments": typeof ExperimentsIndexRoute
  "/projects": typeof ProjectsIndexRoute
  "/projects/$projectKey/memory": typeof ProjectsProjectKeyMemoryRoute
  "/projects/$projectKey/reviews": typeof ProjectsProjectKeyReviewsRoute
  "/projects/$projectKey/workspace": typeof ProjectsProjectKeyWorkspaceRoute
  "/projects/$projectKey": typeof ProjectsProjectKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/chat": typeof ChatRoute
  "/live": typeof LiveRoute
  "/settings": typeof SettingsRoute
  "/projects/$projectKey": typeof ProjectsProjectKeyRouteWithChildren
  "/experiments/": typeof ExperimentsIndexRoute
  "/projects/": typeof ProjectsIndexRoute
  "/projects/$projectKey/memory": typeof ProjectsProjectKeyMemoryRoute
  "/projects/$projectKey/reviews": typeof ProjectsProjectKeyReviewsRoute
  "/projects/$projectKey/workspace": typeof ProjectsProjectKeyWorkspaceRoute
  "/projects/$projectKey/": typeof ProjectsProjectKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/chat"
    | "/live"
    | "/settings"
    | "/projects/$projectKey"
    | "/experiments/"
    | "/projects/"
    | "/projects/$projectKey/memory"
    | "/projects/$projectKey/reviews"
    | "/projects/$projectKey/workspace"
    | "/projects/$projectKey/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/chat"
    | "/live"
    | "/settings"
    | "/experiments"
    | "/projects"
    | "/projects/$projectKey/memory"
    | "/projects/$projectKey/reviews"
    | "/projects/$projectKey/workspace"
    | "/projects/$projectKey"
  id:
    | "__root__"
    | "/"
    | "/chat"
    | "/live"
    | "/settings"
    | "/projects/$projectKey"
    | "/experiments/"
    | "/projects/"
    | "/projects/$projectKey/memory"
    | "/projects/$projectKey/reviews"
    | "/projects/$projectKey/workspace"
    | "/projects/$projectKey/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LiveRoute: typeof LiveRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRouteWithChildren
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/live": {
      id: "/live"
      path: "/live"
      fullPath: "/live"
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/chat": {
      id: "/chat"
      path: "/chat"
      fullPath: "/chat"
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/": {
      id: "/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/experiments/": {
      id: "/experiments/"
      path: "/experiments"
      fullPath: "/experiments/"
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/$projectKey": {
      id: "/projects/$projectKey"
      path: "/projects/$projectKey"
      fullPath: "/projects/$projectKey"
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/$projectKey/": {
      id: "/projects/$projectKey/"
      path: "/"
      fullPath: "/projects/$projectKey/"
      preLoaderRoute: typeof ProjectsProjectKeyIndexRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    "/projects/$projectKey/workspace": {
      id: "/projects/$projectKey/workspace"
      path: "/workspace"
      fullPath: "/projects/$projectKey/workspace"
      preLoaderRoute: typeof ProjectsProjectKeyWorkspaceRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    "/projects/$projectKey/reviews": {
      id: "/projects/$projectKey/reviews"
      path: "/reviews"
      fullPath: "/projects/$projectKey/reviews"
      preLoaderRoute: typeof ProjectsProjectKeyReviewsRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
    "/projects/$projectKey/memory": {
      id: "/projects/$projectKey/memory"
      path: "/memory"
      fullPath: "/projects/$projectKey/memory"
      preLoaderRoute: typeof ProjectsProjectKeyMemoryRouteImport
      parentRoute: typeof ProjectsProjectKeyRoute
    }
  }
}

interface ProjectsProjectKeyRouteChildren {
  ProjectsProjectKeyMemoryRoute: typeof ProjectsProjectKeyMemoryRoute
  ProjectsProjectKeyReviewsRoute: typeof ProjectsProjectKeyReviewsRoute
  ProjectsProjectKeyWorkspaceRoute: typeof ProjectsProjectKeyWorkspaceRoute
  ProjectsProjectKeyIndexRoute: typeof ProjectsProjectKeyIndexRoute
}

const ProjectsProjectKeyRouteChildren: ProjectsProjectKeyRouteChildren = {
  ProjectsProjectKeyMemoryRoute: ProjectsProjectKeyMemoryRoute,
  ProjectsProjectKeyReviewsRoute: ProjectsProjectKeyReviewsRoute,
  ProjectsProjectKeyWorkspaceRoute: ProjectsProjectKeyWorkspaceRoute,
  ProjectsProjectKeyIndexRoute: ProjectsProjectKeyIndexRoute,
}

const ProjectsProjectKeyRouteWithChildren =
  ProjectsProjectKeyRoute._addFileChildren(ProjectsProjectKeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LiveRoute: LiveRoute,
  SettingsRoute: SettingsRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRouteWithChildren,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
